### ISSUE TITLE
[Evaluación ESTÁTICA] [Issue #5] "La clase NotesDbAdapter contiene un sustantivo plural, debería ser singular"

### ISSUE THREAD

**Issue by LegenDanny24** [ivsm/notas-vv#5]
[Posible solución]: Refactorizar el nombre de la clase.

**Comment by miguel-latre** [comment]
En realidad, la regla de comprobación hace referencia al sustantivo que debe ser el núcleo del identificador. En este caso "Adapter", que está en singular. Por contra, yo hubiera llamado al otro "DbAdapter" `CategoriesDbAdapter`
