### ISSUE TITLE
[Evaluación ESTÁTICA] [Issue #6] "Los atributos comienzan por una minúscula que NO es parte de un sustantivo común"

### ISSUE THREAD

**Issue by LegenDanny24** [ivsm/notas-vv#6]
[Posible solución]: Renombrar los atributos.

**Comment by LegenDanny24** [comment]
[Solucionado]: Se han renombrado los atributos para que todos partan de un sustantivo común y con minúsculas.

**Comment by LegenDanny24** [comment]
Añadida etiqueta.

**Comment by miguel-latre** [comment]
Aquí el problema está en el enunciado de las listas de comprobación. Debería decir que el núcleo del identificador de un atributo debería ser un sustantivo (y empezar por él si el identificador está en castellano o acabar por él si está en inglés) Lo corregiremos para el año que viene :(
