### ISSUE TITLE
[Evaluación ESTÁTICA] [Issue #7] "Se ven más de 6 clases en el diagrama de diseño"

### ISSUE THREAD

**Issue by LegenDanny24** [ivsm/notas-vv#7]
[Posible solución]: Reducir las clases que no sean expresamente relevantes.

**Comment by sarudego** [comment]
[No se solucionará] La mayoría son clases de Android que contienen funciones de Android usadas en el proyecto.

**Comment by miguel-latre** [comment]
En este caso, aunque se trate de un total de 11 clases, están muy bien distribuidas en el diagrama, y además muestran perfectamente el _patrón_ de replicación que se siguió para añadir las categorías.
