### ISSUE TITLE
[Evaluación ESTÁTICA] [Issue #8] "Hay dos relaciones de no herencia que se sitúan verticalmente" 

### ISSUE THREAD

**Issue by LegenDanny24** [ivsm/notas-vv#8]
[Posible solución]: Situarlas en plano horizontal.

**Comment by LegenDanny24** [comment]
[No se solucionará]: Se mantienen las relaciones así por legibilidad.

**Comment by miguel-latre** [comment]
Efectivamente, como comentaba en el _issue_ #7 , las clases están muy bien distribuidas en el diagrama. De todas formas, sin necesidad de colocar las clases en otro sitio, es posible hacer en ambos casos que las relaciones salgan de los laterales de las clases y no de la parte superior e inferior de las mismas. Cuando se sigue el convenio vertical-herencia / horizontal-relación, este _truco_ contribuye a aumentar la legibilidad.
